export const RouteBase = {
  Home: "/",
  Login: "/login",
  RegisterSame: "/register",
  BarcodeScreen: "/barcode",
  CouponScreen: "/coupon",
  HistoryEMoney: "/history-e-money",
  RegisterSuccess: "/register-success",
  RegisterCancel: "/register-cancel",
  RegisterArara: "/register-arara",
  RegisterAraraCancel: "/register-arara-cancel",
  QAScreen: "/qa",
  BarcodePointScreen: "/barcode-point",
  BarcodeEMoneyScreen: "/barcode-e-money",
  DetailCouponScreen: "/detail-coupon",
  QRCodeCouponScreen: "/qr-code",
  RegisterTMN: "/register-tmn",
  BarcodeTMN: "/barcode-tmn",
  callback: "/callback",
  RegisterWithOnlyPoint: "/register-with-only-point",
};
